### ISSUE TITLE
[Question] Risk of ban or detection?

### ISSUE THREAD

**Issue by samirrah** [MD2K23/VineProductHider#1]
What are the chances of being detected using this script? Would a script of this function be low risk? Or the same high risk as using any other script to do stuff on the Vine site?

**Comment by MD2K23** [comment]
It's only making changes to the content being displayed in your browser after it's been received from Amazon, not interfacing with Amazon in any way, so no reason for it to be of any risk.

**Comment by samirrah** [comment]
ty for the response! i as well did more research into userscripts as well and of course, found similar responses.

**Comment by samirrah** [comment]
ty for the response! i as well did more research into userscripts as well and of course, found similar responses.
